### ISSUE TITLE
Could you please add cryptocurrency as well?

### ISSUE THREAD

**Issue by KurtDeGreeff** [markwragg/PowerShell-CurrencyConverter#1]
I'm wondering if the api also provides cryptocurrencies like Bitcoin, Ethereum,..

**Comment by markwragg** [comment]
The API that this module depends on doesn't currently provide cryptocurrency rates. It wouldn't be too difficult to implement a wrapper for another API that does provide them though.

**Comment by markwragg** [comment]
The module now supports crypto currencies via the CoinBase API. There are 3 new cmdlets: `Convert-CryptoCurrency`, `Get-CryptoCurrency` and `Get-CryptoExchangeRate` that support the conversion of crypto and non-crypto currencies. I've also updated `Format-Currency` to support formatting some crypto currency symbols.

Update to version 0.0.7 of the module to get the new cmdlets: https://www.powershellgallery.com/packages/CurrencyConverter/0.0.7
